name: Add Issue to Project

on:
  issues:
    types:
      - opened


jobs:
  add-to-project:
    name: Add Issue to Project
    runs-on: self-hosted
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.JUNO_CI_APP_ID }}
          private-key: ${{ secrets.JUNO_CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/juno-fx/projects/12
          github-token: ${{ steps.generate-token.outputs.token }}

